source 'https://rubygems.org'

gem 'jekyll'
gem 'jekyll-paginate'
gem 'pygments.rb'
gem 'sass'
gem 'octopress', '~> 3.0.0.rc.12'
gem 'jekyll-sitemap'
gem 'kramdown'
gem 'jekyll_inline_highlight'
gem 'jekyll-include-cache'
